name: ${STACK}

services:
  web:
    image: nginx:1.27-alpine
    restart: unless-stopped
    volumes:
      - "./www:/usr/share/nginx/html:ro"
      - "./logs/runtime:/var/log/nginx"
    networks:
      - "${TRAEFIK_NETWORK:-proxy}"
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=${TRAEFIK_NETWORK}"

      - "traefik.http.routers.${STACK}-${URI_SCHEME}.rule=Host(`${APP_HOST}`)"
      - "traefik.http.routers.${STACK}-${URI_SCHEME}.entrypoints=${TRAEFIK_ENTRYPOINT:-web}"
      - "traefik.http.routers.${STACK}-${URI_SCHEME}.priority=10"
      - "traefik.http.routers.${STACK}-${URI_SCHEME}.middlewares=${STACK}-${URI_SCHEME}-redirect"
      - "traefik.http.routers.${STACK}-${URI_SCHEME}.service=${STACK}-${URI_SCHEME}"
      - "traefik.http.routers.${STACK}-${URI_SCHEME}.tls=${TRAEFIK_TLS:-false}"
      - "traefik.http.services.${STACK}.loadbalancer.server.port=80"
      - "traefik.http.middlewares.${STACK}-${URI_SCHEME}-redirect.redirectscheme.scheme=https"
      - "traefik.http.middlewares.${STACK}-${URI_SCHEME}-redirect.redirectscheme.permanent=false"

      - "traefik.http.routers.${STACK}-https.rule=Host(`${APP_HOST}`)"
      - "traefik.http.routers.${STACK}-https.entrypoints=websecure"
      - "traefik.http.routers.${STACK}-https.priority=10"
      - "traefik.http.routers.${STACK}-https.tls=true"
      - "traefik.http.routers.${STACK}-https.service=${STACK}-https"

      - "solutions.etal.service=web"
      - "solutions.etal.service_tier=frontend"
      - "solutions.etal.managed_by=${MANAGED_BY}"
      - "solutions.etal.service_lifecycle=${LIFECYCLE}"
      - "solutions.etal.project_id=${PROJECT_ID}"
      - "solutions.etal.deployment_id=${DEPLOYMENT_ID}"
      - "solutions.etal.stack=${STACK}"
      - "solutions.etal.data_class=${DATA_CLASS}"
      - "solutions.etal.data_lifecycle=${DATA_LIFECYCLE}"

networks:
  proxy:
    external: true
    name: ${TRAEFIK_NETWORK:-proxy}
