#!/usr/bin/env bash
set -euo pipefail
pm_config_wp() {
    local scopes='application,web,app'
    pm_config_register WORDPRESS_DB_HOST var "$scopes" WORDPRESS_DB_HOST optional
    pm_config_register WORDPRESS_DB_NAME var "$scopes" WORDPRESS_DB_NAME optional
    pm_config_register WORDPRESS_DB_USER secret "$scopes" WORDPRESS_DB_USER optional
    pm_config_register WORDPRESS_DB_PASSWORD secret "$scopes" WORDPRESS_DB_PASSWORD optional
    pm_config_register WP_ENV var "$scopes" WP_ENV optional
}
