server {
    listen 80 default_server;
    server_name _;

    root /usr/share/nginx/html;
    index index.html;

    access_log /var/log/nginx/access.log;
    error_log  /var/log/nginx/error.log warn;

    location = /healthz {
        access_log off;
        default_type application/json;
        return 200 '{"ok":true,"status":"alive"}';
    }

    location = /readyz {
        access_log off;
        default_type application/json;
        return 200 '{"ok":true,"status":"ready"}';
    }

    location / {
        try_files $uri $uri/ /index.html;
    }
}
